USE [master]
GO
/****** Object:  Database [ETRADE4]    Script Date: 11/1/2020 4:33:50 PM ******/
CREATE DATABASE [ETRADE4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ETRADE4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ETRADE4.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ETRADE4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ETRADE4_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ETRADE4] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ETRADE4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ETRADE4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ETRADE4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ETRADE4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ETRADE4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ETRADE4] SET ARITHABORT OFF 
GO
ALTER DATABASE [ETRADE4] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ETRADE4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ETRADE4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ETRADE4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ETRADE4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ETRADE4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ETRADE4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ETRADE4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ETRADE4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ETRADE4] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ETRADE4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ETRADE4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ETRADE4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ETRADE4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ETRADE4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ETRADE4] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ETRADE4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ETRADE4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ETRADE4] SET  MULTI_USER 
GO
ALTER DATABASE [ETRADE4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ETRADE4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ETRADE4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ETRADE4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ETRADE4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ETRADE4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ETRADE4', N'ON'
GO
ALTER DATABASE [ETRADE4] SET QUERY_STORE = OFF
GO
USE [ETRADE4]
GO
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[COUNTRYID] [tinyint] NULL,
	[CITYID] [smallint] NULL,
	[TOWNID] [int] NULL,
	[DISTRICTID] [int] NULL,
	[POSTALCODE] [varchar](10) NULL,
	[ADDRESSTEXT] [varchar](500) NULL,
 CONSTRAINT [PK_ADDRESS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITIES]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITIES](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[COUNTRYID] [tinyint] NULL,
	[CITY] [varchar](50) NULL,
 CONSTRAINT [PK_CITIES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COUNTRIES]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUNTRIES](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[COUNTRY] [varchar](50) NULL,
 CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISTRICTS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISTRICTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TOWNID] [int] NULL,
	[DISTRICT] [varchar](50) NULL,
 CONSTRAINT [PK_DISTRICTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICEDETAILS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICEDETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICEID] [int] NULL,
	[ORDERDETAILID] [int] NULL,
	[ITEMID] [int] NULL,
	[AMOUNT] [int] NULL,
	[UNITPRICE] [decimal](18, 4) NULL,
	[LINETOTAL] [decimal](18, 4) NULL,
 CONSTRAINT [PK_INVOICEDETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICES]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[DATE_] [datetime] NULL,
	[ADDRESSID] [int] NULL,
	[CARGOFICHENO] [varchar](20) NULL,
	[TOTALPRICE] [decimal](18, 4) NULL,
 CONSTRAINT [PK_INVOICES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEMS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEMS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEMCODE] [varchar](50) NULL,
	[ITEMNAME] [varchar](100) NULL,
	[UNITPRICE] [float] NULL,
	[CATEGORY1] [varchar](50) NULL,
	[CATEGORY2] [varchar](50) NULL,
	[CATEGORY3] [varchar](50) NULL,
	[CATEGORY4] [varchar](50) NULL,
	[BRAND] [varchar](50) NULL,
 CONSTRAINT [PK_ITEMS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERDETAILS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERDETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[ITEMID] [int] NULL,
	[AMOUNT] [int] NULL,
	[UNITPRICE] [decimal](18, 4) NULL,
	[LINETOTAL] [decimal](18, 4) NULL,
 CONSTRAINT [PK_ORDERDETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[DATE_] [datetime] NULL,
	[TOTALPRICE] [decimal](18, 4) NULL,
	[STATUS_] [tinyint] NULL,
	[ADDRESSID] [int] NULL,
 CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENTS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[PAYMENTTYPE] [tinyint] NULL,
	[DATE_] [datetime] NULL,
	[ISOK] [bit] NULL,
	[APPROVECODE] [varchar](100) NULL,
	[PAYMENTTOTAL] [decimal](18, 4) NULL,
 CONSTRAINT [PK_PAYMENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TOWNS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOWNS](
	[ID] [int] NOT NULL,
	[CITYID] [smallint] NULL,
	[TOWN] [varchar](50) NULL,
 CONSTRAINT [PK_TOWNS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 11/1/2020 4:33:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME_] [varchar](50) NULL,
	[PASSWORD_] [varchar](50) NULL,
	[NAMESURNAME] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[GENDER] [varchar](1) NULL,
	[BIRTHDATE] [date] NULL,
	[CREATEDDATE] [datetime] NULL,
	[TELNR1] [varchar](15) NULL,
	[TELNR2] [varchar](15) NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX1]    Script Date: 11/1/2020 4:33:50 PM ******/
CREATE NONCLUSTERED INDEX [IX1] ON [dbo].[ADDRESS]
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ETRADE4] SET  READ_WRITE 
GO
