USE ETRADE4
/*
Generate a detailed report.
*/

SELECT
	-- USER INFO
	U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD, 
	-- ADDRESS INFO
	CI.CITY AS IL, T.TOWN AS ILCE, D.DISTRICT AS SEMT, A.ADDRESSTEXT AS ACIKADRES,
	-- ORDER INFO
	O.ID AS SIPARISID, O.DATE_ AS TARIH, O.TOTALPRICE AS TOPLAMTUTAR,
	-- PAYMENT INFO
	P.DATE_ AS ODEMETARIHI, P.APPROVECODE AS BANKAONAYKODU,
	-- INVOICE INFO
	I.DATE_ AS FATURATARIHI, I.CARGOFICHENO AS KARGOFISNO,
	-- ORDERDETAILS AND ITEM INFO
	OD.LINETOTAL AS SATIRTOPLAM
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
-- conditions
WHERE 
	O.ID = 2000
	--U.NAMESURNAME = 'Ýlayda KAYGUN'

-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
/*
ORDERS BY CITIES
*/

SELECT
	CI.CITY,
	SUM(OD.LINETOTAL) AS TOPLAMSATIS_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSATIS_MIKTARI,
	COUNT(OD.ID) AS TOPLAMSATIS_SAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
-- conditions
--WHERE 
--	O.ID = 2000
	--U.NAMESURNAME = 'Ýlayda KAYGUN'
GROUP BY
	CI.CITY
ORDER BY
	SUM(OD.LINETOTAL) DESC,
	COUNT(OD.ID) DESC,
	CI.CITY


-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
/*
ORDER DISTRIBUTION BY ITEM CATEGORIES
*/

SELECT
	ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4,
	SUM(OD.LINETOTAL) AS TOPLAMSATIS_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSATIS_MIKTARI,
	COUNT(OD.ID) AS TOPLAMSATIS_SAYISI,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
-- conditions
WHERE
	ITM.CATEGORY1='BEBEK'
GROUP BY
	ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4
ORDER BY
	SUM(OD.LINETOTAL) DESC,
	COUNT(OD.ID) DESC,
	ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4

-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
/*
ORDER DISTRIBUTION BY DATE
*/

SELECT
	--CONVERT(date, O.DATE_) TARIH,
	DATEPART(YEAR, O.DATE_) YIL,
	DATEPART(MONTH, O.DATE_) AY,
	CASE
		WHEN DATEPART(MONTH, O.DATE_)=1 THEN 'OCAK'
		WHEN DATEPART(MONTH, O.DATE_)=2 THEN 'ÞUBAT'
		WHEN DATEPART(MONTH, O.DATE_)=3 THEN 'MART'
		WHEN DATEPART(MONTH, O.DATE_)=4 THEN 'NÝSAN'
		WHEN DATEPART(MONTH, O.DATE_)=5 THEN 'MAYIS'
		WHEN DATEPART(MONTH, O.DATE_)=6 THEN 'HAZÝRAN'
		WHEN DATEPART(MONTH, O.DATE_)=7 THEN 'TEMMUZ'
		WHEN DATEPART(MONTH, O.DATE_)=8 THEN 'AÐUSTOS'
		WHEN DATEPART(MONTH, O.DATE_)=9 THEN 'EYLÜL'
		WHEN DATEPART(MONTH, O.DATE_)=10 THEN 'EKÝM'
		WHEN DATEPART(MONTH, O.DATE_)=11 THEN 'KASIM'
		WHEN DATEPART(MONTH, O.DATE_)=12 THEN 'ARALIK'
	END AS AYADI,
	SUM(OD.LINETOTAL) AS TOPLAMSATIS_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSATIS_MIKTARI,
	COUNT(OD.ID) AS TOPLAMSATIS_SAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
-- conditions
--WHERE
--	ITM.CATEGORY1='BEBEK'
GROUP BY
	DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
ORDER BY
	DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)

/*
GROUP BY PAYMENT TYPE
*/
SELECT distinct PAYMENTTYPE
FROM PAYMENTS

SELECT 
DATEPART(YEAR, DATE_) AS YIL,
CASE
		WHEN DATEPART(MONTH, DATE_)=1 THEN 'OCAK'
		WHEN DATEPART(MONTH, DATE_)=2 THEN 'ÞUBAT'
		WHEN DATEPART(MONTH, DATE_)=3 THEN 'MART'
		WHEN DATEPART(MONTH, DATE_)=4 THEN 'NÝSAN'
		WHEN DATEPART(MONTH, DATE_)=5 THEN 'MAYIS'
		WHEN DATEPART(MONTH, DATE_)=6 THEN 'HAZÝRAN'
		WHEN DATEPART(MONTH, DATE_)=7 THEN 'TEMMUZ'
		WHEN DATEPART(MONTH, DATE_)=8 THEN 'AÐUSTOS'
		WHEN DATEPART(MONTH, DATE_)=9 THEN 'EYLÜL'
		WHEN DATEPART(MONTH, DATE_)=10 THEN 'EKÝM'
		WHEN DATEPART(MONTH, DATE_)=11 THEN 'KASIM'
		WHEN DATEPART(MONTH, DATE_)=12 THEN 'ARALIK'
	END AS AYADI,
--PAYMENTTYPE AS ODEMETURU,
CASE
	WHEN PAYMENTTYPE=1 THEN 'NAKÝT'
	WHEN PAYMENTTYPE=2 THEN 'KREDÝ KARTI'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS ODEME_MIKTARI
FROM 
	PAYMENTS
GROUP BY
	DATEPART(YEAR, DATE_), DATEPART(MONTH, DATE_), 
	PAYMENTTYPE
ORDER BY
	DATEPART(YEAR, DATE_), DATEPART(MONTH, DATE_),
	PAYMENTTYPE

-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* Müþteri Memnuniyeti -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
/*
CALCULATE AVERAGE DELIVERY TIME
*/

-- delivery times by orderid
SELECT
	O.ID AS SIPARISID,
	O.DATE_ AS SIPARISTARIHI,
	I.DATE_ AS FATURATARIHI,
	DATEDIFF(HOUR, O.DATE_, I.DATE_) AS GECENZAMAN_SAAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID

-- min, max, avg delivery times by orderid
SELECT
	MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Min_GECENZAMAN_SAAT,
	MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Max_GECENZAMAN_SAAT,
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Avg_GECENZAMAN_SAAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID

-- FIND AN UNSATISFIED CUSTOMERS
SELECT
	U.ID, U.NAMESURNAME,
	MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Min_GECENZAMAN_SAAT,
	MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Max_GECENZAMAN_SAAT,
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Avg_GECENZAMAN_SAAT,
	SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
	COUNT(O.ID) AS SIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY
	U.ID, U.NAMESURNAME
HAVING
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) > 28
ORDER BY
	SUM(O.TOTALPRICE) DESC
	--AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) DESC


-- DELIVERY TIMES BY "YEAR AND MONTH"
SELECT
	DATEPART(YEAR, O.DATE_) AS YIL, DATEPART(MONTH, O.DATE_) AS AY,
	MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Min_GECENZAMAN_SAAT,
	MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Max_GECENZAMAN_SAAT,
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Avg_GECENZAMAN_SAAT,
	SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
	COUNT(O.ID) AS SIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY
	DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
--HAVING
--	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) > 28
ORDER BY
	DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)


-- DELIVERY TIMES BY CITIES
SELECT
	CI.CITY SEHIR,
	MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Min_GECENZAMAN_SAAT,
	MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Max_GECENZAMAN_SAAT,
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS Avg_GECENZAMAN_SAAT,
	SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
	COUNT(O.ID) AS SIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	-- Join addresses
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CI ON CI.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	-- Join INFO TABLES
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY
	CI.CITY
ORDER BY
	AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) DESC, MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) DESC, MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)),
	SUM(O.TOTALPRICE),
	CI.CITY