USE ETRADE2

-- SEE THE ROWS
SELECT TOP 100 *
FROM SALES
GO

SELECT TOP 100 [ITEMNAME], [BRAND], [AMOUNT], [PRICE], [TOTALPRICE]
FROM SALES
GO

SELECT COUNT(ITEMNAME), MIN(AMOUNT), MAX(PRICE), AVG(PRICE), SUM(TOTALPRICE), SUM(TOTALPRICE) / COUNT(ITEMNAME)
FROM SALES
GO

DECLARE @NumITEMNAME INT;
SELECT @NumITEMNAME = COUNT(ITEMNAME)
FROM SALES;
SELECT @NumITEMNAME;
GO


-- -- group by --
SELECT *
FROM SALES

select COUNT(BRAND), BRAND from SALES
group by BRAND;

select COUNT(CUSTOMERGENDER), CUSTOMERGENDER from SALES
group by CUSTOMERGENDER;
