USE ETRADE

SELECT  [Id], [CUSTOMERNAME], [CITY], [DISTRICT], [BIRTHDATE], [GENDER], [NATION], [AGE]
FROM CUSTOMERS AS C
WHERE CITY IN ('ÝSTANBUL', 'ANKARA', 'ÝZMÝR', 'BURSA') AND GENDER='E' AND C.AGE<40