-- INTER SQL DATE FORMAT: '1990-01-01'->'19900101'(STANDART)
USE ETRADE
SELECT * FROM CUSTOMERS
--WHERE CITY IN ('ÝSTANBUL', 'ANKARA', 'ÝZMÝR', 'BURSA')  -- EQUAL TO CITY='iSTANBUL' OR CITY='ANKARA' OR CITY='ÝZMÝR' OR CITY='BURSA'

--WHERE CUSTOMERNAME LIKE '%NUR%'
-- WHERE CUSTOMERNAME LIKE '%TAL'  -- '%' i don't know but complete. It is equals to unix shell '*'

-- WHERE AGE BETWEEN 22 AND 30

-- WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'

-- WHERE CITY NOT IN ('ÝSTANBUL', 'ÝZMÝR', 'RÝZE')
-- WHERE CITY<>'iSTANBUL'  -- NOT EQUAL, "NOT cýty='iSTANBUL'"

-- WHERE CITY='iSTANBUL'
