CREATE TABLE [ETRADE].[CUSTOMERS]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[CUSTOMERNAME] NVARCHAR(50) NULL,
	[CITY] NVARCHAR(50) NULL,
	[DISTRICT] NVARCHAR(50) NULL,
	[BIRTHDATE] DATETIME NULL,
	[GENDER] NCHAR(1) NULL
)

